### ISSUE TITLE
Ignores are not working with classname selectors starting with a capital letter

### ISSUE THREAD

**Issue by jjblumenfeld** [cazzer/gulp-selectors#28] opened 2017-05-19 16:41 UTC
We are using this to minify selectors when we are generating emails. We have a reset css in-place which overrides some settings on the .ExternalClass which is added in Outlook. We want this rule to be ignored so that it remains when the email is rendered in outlook.

Seems like:
https://github.com/cazzer/gulp-selectors/blob/master/lib/utils/expressions.js#L1

Could be updated to:
var selectorName = '(-?[_a-zA-Z]+[_\\w-]*)';
To allow this type of selector to be passed through. Is that possible?

**Comment by cazzer** [comment] 2017-05-19 17:09
Hi @jjblumenfeld, I'm glad to hear this package has been useful for you! Since your goal is to ignore a specific class, can you use the `ignore` option to specifically exclude the `.ExternalClass`? Here's is how that would be written:
```js
gs.run({...}, {
  classes: ['ExternalClass']
}
```

Let me know if this works!

**Comment by jjblumenfeld** [comment] 2017-05-19 17:26
Hi
Unfortunately it seems that selectors which start with a capital letter cannot be ignored.

**Comment by cazzer** [comment] 2017-05-19 17:54
Ah, I see your issue now. I checked it out locally and was able to reproduce your issue. If you can submit a PR with a test to cover this case I'll happily merge it! Just make sure not to drop the `_` from the expression, I believe it should be `'(-?[_a-zA-Z]+[\w-]*)'`.

**Comment by jjblumenfeld** [comment] 2017-05-19 20:07
Great. Done!

**Comment by cazzer** [comment] 2017-05-20 20:17
Thanks for the PR, I merged it and bumped to version [0.1.10](https://www.npmjs.com/package/gulp-selectors). Let me know if you continue experiencing issues and I'll reopen this issue.

**Closed by cazzer** 2017-05-20 20:17 UTC
